

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from 'wagmi'
import { config, projectId } from '@/config'
import Header from "@/app/components/common/Header-old";
import Footer from "@/app/components/common/Footer";
import Web3ModalProvider from "@/context";
import { createWeb3Modal } from "@web3modal/wagmi/react";
import { headers } from 'next/headers'




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider initialState={initialState}>
          <Header title="Colibridge" />
          {children}
          <Footer />
        </Web3ModalProvider>

      </body>
    </html>
  );
}
